application: gcp-ug-dev
module: default
version: 20150812a
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /about
  static_files: about.html
  upload: about.html
- url: /event
  static_files: event.html
  upload: event.html
- url: /join
  static_files: join.html
  upload: join.html
- url: /template
  static_dir: template
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /font
  static_dir: font
- url: /admin/.*
  script: _go_app
  login: admin
- url: /cron/.*
  script: _go_app
  login: admin
- url: /.*
  script: _go_app