application: gcp-ug
version: 20141211
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /group
  static_files: group.html
  upload: group.html
- url: /event
  static_files: event.html
  upload: event.html
- url: /template
  static_dir: template
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /font
  static_dir: font
- url: /.*
  script: _go_app